#! /usr/bin/env bash

set -e
RUN_COMMAND="hypercorn webapp.app:app --bind $1 --worker-class asyncio"

if [ "${QUART_DEBUG}" = true ] || [ "${QUART_DEBUG}" = 1 ]; then
    RUN_COMMAND="${RUN_COMMAND} --reload --log-level debug"
fi

${RUN_COMMAND}
